### ISSUE TITLE
Add property with the number of likes

### ISSUE THREAD

**Issue by fgsfds** [craftersmine/SteamGridDB.NET#10]
**Describe the solution you'd like**
Add a new property to SteamGridDb* types that holds a number of likes that current image has.

**Additional context**
Maybe it's already there and I'm just not seeing it, but both upvotes and score properties are obsolete and don't represent number of likes.

**Comment by craftersmine** [comment]
They are already in the code, like https://github.com/craftersmine/SteamGridDB.NET/blob/dd8622f200d084d6b74eecc27905b4ee38d2a2d5/craftersmine.SteamGridDB.Net/SteamGridDbObject.cs#L92 or https://github.com/craftersmine/SteamGridDB.NET/blob/dd8622f200d084d6b74eecc27905b4ee38d2a2d5/craftersmine.SteamGridDB.Net/SteamGridDbObject.cs#L27

But the thing is that they are deprecated by SteamGridDB as it's developer says

![image](https://github.com/craftersmine/SteamGridDB.NET/assets/11241645/097df1de-f596-4da9-b66b-38f7916555fa)

And because of that, they are marked with Obsolete attribute.
